server:
  port: 8098
spring:
  application:
    name: cart-service
  redis:
    host: 192.168.192.128
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka/
    registry-fetch-interval-seconds: 10
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
leyou:
  jwt:
    pubKeyPath: C:\\Users\\Hello\\Desktop\\key\\rsa.pub
    cookieName: LY_TOKEN